### ISSUE TITLE
@iwsio/json-csv-core/types does not exist

### ISSUE THREAD

**Issue by khuynhepi** [iwsllc/json-csv#60]
Getting this error when transpiling with `tsc`
```
node_modules/@iwsio/json-csv-node/dist/exporter.d.cts:3:36 - error TS2307: Cannot find module '@iwsio/json-csv-core/types' or its corresponding type declarations.

import type { ExportOptions } from '@iwsio/json-csv-core/types';
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by khuynhepi** [comment]
It seems like installing `@iwsio/json-csv-core` does not work either

**Comment by khuynhepi** [comment]
Looks like the path should be 
```
import type { ExportOptions } from '@iwsio/json-csv-core/dist/types
```

**Comment by nathanb** [comment]
Just seeing this. I'll check it out! Thanks @khuynhepi

**Comment by nathanb** [comment]
@khuynhepi I see what's going on. This is due to your `tsconfig.json` likely using `moduleResolution: 'Node'` instead of `Node16` or `NodeNext`. The difference between `Node` and the others is that Node16 and newer will use the `package.json` `exports` prop to map subpaths to modules on disk. The type import pattern is by convention too, so when you import `@iwsio/json-csv-core/exporter`, Typescript will resolve the module at the path: `./dist/exporter.js` and its matching type definitions `./dist/exporter.d.ts`. 

TL'DR: If you're using `moduleResolution: "Node"`, you need to use the relative path from the root of the module.  If you're using `Node16` or `NodeNext`, it supports sub-path exports. 

Options:
 - Switching to `Node16` should get you most of the module resolution behavior you're used to and support for the sub-path export.
 - Keeping `Node` just means you have to import the disk module. Typescript should see types adjacent to it on disk.

**Comment by nathanb** [comment]
More info at https://www.typescriptlang.org/tsconfig/#moduleResolution

**Comment by nathanb** [comment]
Also, just FYI, there were some weird resolution issues between ESlint and Typescript. I'm shoring up the config in the next PR. #61

**Comment by khuynhepi** [comment]
thanks @nathanb. I was able to successfully transpile. However, I am still unsure on the eslint issue you are talking about. 

```
  8:31  error  Unable to resolve path to module '@iwsio/json-csv-core/types'  import/no-unresolved
  ```

**Comment by khuynhepi** [comment]
ahh seems like adding 
```
  "settings": {
    "import/resolver": {
      "typescript": {}
    }
  }
  ``` 
  
  did it

**Comment by nathanb** [comment]
Awesome! Great work!
